name: Build and Deploy Code

on: [push, pull_requesst]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hey
        runs: echo "hey ainur"
